#+title: Notes on the Gospel of Matthew (KJV)

* Matthew 3

Kingdom of Heaven and the Kingdome of God - are but two phrases for the same
thing. They mean, not barely a future happy state, in heaven, but a state to be
enjoyed on earth: the proper disposition of the glory of heaven, rather than the
possession of it.

John the Baptist - Like Elijah, in whose spirit and power he came...
John had his raiment of camels' hair - coarse and rought, suiting his character
and doctrine... Just as John the baptist paved the way for Jesus, this type of
spirit is necessary to to preceed the spirit of Jesus (Joseph, Jeremiah?)

What are the various spirits of the prophets
  1. Joseph spirit - gentle, soft, and loving (maybe passive) yet with zeal
  2. Elijah - course, rough sharp, firey...

* Matthew 4

** Jesus' Temptation: Matthew 4:1-10
When Jesus was tempted, Matthew 4:4, "But he answered and said, It is written,
Man shall not live by bread alone, but by every word that proceedeth out of the
mouth of God."

Matthew 4:6,7 "And saith unto him, If thou be the Son of God, cast thyself down:
for it is written, He shall give his angels charge concerning thee: and in their
hands they shall bear thee up, lest at any time thou dash thy foot against a
stone. Jesus said unto him, It is written again, Thou Shalt not tempt the Lord
thy God.
> Psalm 91:11,12 - For he shall give his angels charge over thee, to keep thee in
all they ways. They shall bear thee up in their hands, lest thou day they foot
against a stone.
Matthew 4:8-11
We see that the devil is well versed in the Word of God. The last temptation,
Satan reveals himself by offering the kingdoms of the world and all the glory of
them to Jesus, except that he must fall down and worship him (revealing his true
identity as Satan). "Then saith Jesus unto him, Get thee hence, Satan: for it is
written, Thou shalt worship the Lord thy God, and him only shalt thou serve. Then
the devil leaveth him, and, behold, angels came and ministered unto him.

** Jesus calls his disciples Matthew 4:18-22
Jesus calls Simon (called Peter) and his brother Andrew as well as James the son
of Zebedee and John his brother.

Matt 4:19 - "And he saith unto them, Follow me, and I will make you fishers of
men."

Matt 4:23 - The Gospel of the kingdom: The Gospel, that is, the joyous message,
is the proper name of our religion - as will be amply verified in all who
earnestly and perseveringly embrace it.

* Matthew 5
** Matthew 5:3
Blessed are the poor in spirit: for theirs is the kingdom of heaven.

** Matthew 5:5
Blessed are the meek: for they shall inherit the earth.

** Matthew 5:8
Blessed are the pure in heart: for they shall see God.

** Matthew 5:9
Blessed are the peacemakers: for they shall be called the children of God.

* Mathew 6
** Matthew 6:31-34 (KJV)
"Therefore take no thought, saying, What shall we eat? or, What shall we drink?
or, Wherewithal shall we be clothed? (For after all these things do the Gentiles
seek:) for your heavenly Father knoweth that ye have need of all these
things. But seek ye first the kingdom of God, and his righteousness; and all
these things shall be added unto you. Take therefore no thought for the morrow:
for the morrow shall take thought for the things of itself. Sufficient unto the
day is the evil thereof."
