#+title: Testimony - Erik, where are you?

* Title: Erik where are you? (30 min version)
** Epoch of Salvation
God called me in middle school, led through the prayer of salvation by Pastor White.

** Epoch of the call of God
God calling me to church through the youth pastor at Grace temple, while I was
getting a burrito.

** Epoch of prophesy & miracles
The temultous life with George and God first speaking to me in a prophetic way to
use me to save my mom from george bruttally beating her.

** Epoch of discipleship
My call to become closer to God at UCSC through discipleship with Philip Taynton.

** Epoch of prophetic word (Daniel)
My first encounter with the Holy Spirit, the epoch of Daniel: Matthew, Lucas and
I and my first receipt of a prophetic word in my life, Genesis 50:20 "You
intended to harm me, but God intended it for good to accomplish what is now being
done, the saving of many lives."

** Epoch of Impartation of the Holy Spirt & realization of prophesy
Impartation of the Holy Spirit, gifts of the Spirit - the epoch of freedom!
Freedom House church

* Title: Erik where are you? (10 min version)


* Title: Erik where are you? (3 min version)
God called me at a very young age, I was in middle school when I first accepted
Christ into my life - this actually happened when I used to work with my Dad on
the weekends, since my Mom and Dad divorced when I was only four years old. It
was at a church that gathered in a school cafeteria. Little did I know my life
would be forever changed beyond that point. Though, I never really commited to
walk a life of faith, to say the least my life lead down many temultous paths
(shadows of the valley of death, if you will). Though, God never left me - time
and time again God would call and lead me back to him. Fast forward to present,
God has called me back through Adam, and this has led me to a new epoch in my
life, one led by the Holy Spirit and many miracles. I have since been
transformed, a decade long habit of drinking instantenously removed - I almost
don't even remember that I loved drinking, this in itself is unimaginable. And
secondly a complete physical transformation, my health has been completely
restored, I have lost 100 lbs, my asthma is completely gone. And God is working
even more miracles in my life, right now as we speak as you can see as I am here
talking to you!
