#+latex_class: article
#+latex_class_options: [a4paper]
#+latex_compiler: pdflatex

#+title: Testimony
#+author: Erik P. Almaraz
#+email: erik@almarazlabs.com
#+date: \today
#+startup: showeverything inlineimages

* Early Life
** Epoch of Salvation
\paragraph{}
God called me in middle school, led through the prayer of salvation by Pastor White.

** Epoch of the call of God
\paragraph{}
God calling me to church through the youth pastor at Grace temple, while I was getting a burrito.

** Epoch of prophesy & miracles
\paragraph{}
The temultous life with George and God first speaking to me in a prophetic way to use me to save my mom from
george bruttally beating her.


* The Call to Adventure
** Epoch of discipleship
\paragraph{}
My call to become closer to God at UCSC through discipleship with Philip Taynton.

\paragraph{}
Here God once again called me, however, through a classmate - his name was Philip Taynton. This was during
the time that I went to UCSC as an undergraduate. While the road to me coming to college was a difficult trek,
it was something that was guided by God, even though at that time I wasn't fully aware of it. I never went
to church with Philip, but maybe once, though he introduced me into the concept of discipleship, merely by
the fact of asking if I would be open to being discipled. I thought this was a really weird question, but
something in my heart knew I needed to say yes and even at that moment I was really excited about it. It
wasn't until after I had said yes, that night that I began to have doubts - this is usually how things work
for me in my mind, the doubts begin to creep in at night. 

\paragraph{}
A life as a Christian at the time seemed boring,
restricted and just plain out fake - most of the poeple I had met in my life who were "Christian" acted
fake, they would generally never admit to anything being bad in their life and whenever you talked with them
everything was always great or hunky-dory. And in my mind and understanding of the Bible this didn't seem to be
inline most definitely with all the stories of the Bible, there is not one story in the Bible that doesn't
have multiple sets of rough patches. Anyways, this is what made me never feel comfortable amongst the Christian
types, the general facade they portraid. But, I guess God wanted to teach me that this was not true and the
only way to do that was to be discipled by Philip! 

\paragraph{}
It was through our friendship, where I learned for the
first time what it was like to have a frienship based in Christ was truely like, and guess what? It wasn't
all hunky-dory! I remember one time Philip once told me that he was tired of seeing my face! That actually
kind of hurt, but then again I may be an overwhelming person to be around, I generally over analyze
everything and question everything to the point that I even exhaust myself - no wonder its the case that I
haven't had many friends in my life, enough to count on one hand with 2 or 3 digits remaining! Anyways, back
to the story. 

\paragraph{}
It was through our friendship, discipleship, that I learned how to pray and depend on
God. Though, much of the walk of faith I learned through this saga in my life was primarily dependent on
Philip's faith and very little of my own. This is because when the time came to graduate and I moved on to
graduate school, I quickly went back to my own ways. At this point I began feel like Jonah - because
destruction tended to alway pursue and unfortunately it also affect those around me.

\paragraph{}
During my discipleship, there was sort of an underground life or background thread as I like to call it was
occuring. I had a set of good friends who weren't really Christian, most notably Pierre - who inevitably had
a very beautiful sister that like me and well I had a huge crush on her, though I never acted on
it. However, when I found out that she started looking for other guys and even dating another guy, it
crushed me and well I resorted to drinking, and drinking very heavily. This ultimately led to me getting a
second DUI - the details I will spare you! However, the result of this situation was loosing my car and
having to do community service in lieu of jail time. 

\paragraph{}
This was all happening while I was being discipled by Philip, actually near the end of my time at UCSC. My
drinking actually started to spiral out of control, not because of quantity or frequency, but because of the
reason why. I was drinking to dround out things, and to be honest I didn't really enjoy it much, but it did
an excellent job at drowning out my thoughts and just giving myself a break from my mind!



** Epoch of prophetic word (Daniel)
\paragraph{}
My first encounter with the Holy Spirit, the epoch of Daniel: Matthew, Lucas and I and my first receipt of a
prophetic word in my life, Genesis 50:20 "You intended to harm me, but God intended it for good to
accomplish what is now being done, the saving of many lives."

\paragraph{}
Fast forward to PhD school at UC Irvine - yes, even though I was at that point a crazy alcoholic, more or
less a binge drinker during the times of duress. And as you know - there isn't a single moment in PhD
school that isn't under duress. So as you can probably imagine - I was a blazing alcoholic throughout my
graduate school career. The fact that I made it there still amazes me to this day, and how I was even able
to make it past the qualification exams, two 8 hour days of tests on all subjects covered in your first two
years there, but also nearly completing a dissertation. Anyways, that isn't the point of this epoch of my life!

\paragraph{}
But, God had met me once again there. This time through an odd fellow named Matthew, Matthew Pevarnik! This
guy hated God, and evey now and then I would mention God to him and he would always go on rants, but we were
drinking buddies - the story of how this came to be I will spare you the details for now. However, he was
pretty isolative and didn't hang out with most people in my PhD class, there was 12 of us and later 13. I
found it odd that he would also call me and ask if I wanted to hang out, most of the time I would say no,
but he would say "I have a 6 pack with your name on it," and well, next thing you know I would be at his
house. Things continued on like this for a while, but little did I know that God had a plan!

\paragraph{}
One day Matthew called me over and well he did the strangest thing - He got rid of his gaming computer that
he was super proud of! I of course brought over my beer and was drinking, he wasn't but he told me that I
should quit, even though he wasn't much of a drinker - I found this turn of events interesting. Later I
found out that a very pretty young lady Victory had asked him to study the Bible with her and man he was
head over heels for her! I knew this was a good thing, despite me being in sin, I still knew what was truly
right and I knew he needed God in his life, and I knew a lot of people who were brought to Christ through a
crush on a girl that they met in church or through Bible study.

\paragraph{}
This new turn of events led us going to a Church called Shepherds church. This was the first time in my life
that I ever committed to going to a church, though I was wasn't necessarily committed on my own will, but
yet again I had the strength through the faith that God imparted through Matthew! Matthew was like Peter, at
least similar in spirit. We led an early life of fishermen! We used to go around the UC Irvine campus
fishing, well mostly him - I was too timid to ask anybody, except the few times when I was forced. We even
went into the Chemistry and Physics building boldly asking people to do Bible studies. This is where I met
Lucas! Lucas was a "goat" as you would say in christianese! He was also a pastor's kid and well very
arrogant. I would later learn, while a much more upright citizen than I, he would spend most of his time
online in atheous blogs debating aethiests! When I first met him, he reminded me exactly what I told you
about the typical christians, outwardly facing - perfect, everything with him was alway hunky-dory! You know
the usual! But, I knew it wasn't and well - I learned that quickly as Lucas, Matthew and I became to be
known as the "Three Musketeers" at Shepherd's Church, as the Pastor would call us!

\paragraph{}
For brevity, I want to mention the highlights of this epoch. Living out my life of faith and prayer, I
really began to know God - because through this fellowship between the three of us, it was really the first
time that I did a deep dive into the Bible, we were literally meditating on the Word of God, day and night -
I was putting much more effort into studying the Bible that I was for my own PhD dissertation! Also, after
we finished a deep dive study of the book of Genesis, we actually as a field trip, built an altar to the
lord, we stacked up some rocks right in from of the rocky plaza type area in front of Natural Sciences II,
the building of demons was we called it - where we would pray every morning. This was a little scary for me,
because we would pray loudly and well I knew all my professors could probably see and did see me!

\paragraph{}
However, setting up that altar was a good thing it in itself discipled a fourth! We met Paul, who later
joined us in a bible study group initiated by Matthew and his girlfriend Victoria - yes, you heard that
correct, they were now boyfriend and girlfriend. We called the Bible study group After God's Heart, AGH in
short. Those were some good times, but also bad times because I began to lose my grip on God, with Matthew
not able to hang out as much - me and Lucas hung out more, and I also started to drink again. Graduate
school became tough and I drank even tougher!

\paragraph{}
This led me to what I call the saga of my prison training. But rather, I got a third DUI and was sentenced
to 1 year in Jail. In 2x playback mode, my PhD crumbled, while I had a very successful start and a nearly
completed dissertation I was ahead - most PhD students don't go into their Advancement to Candidacy with a
nearly completed dissertation, yet despite that I failed out. I would go into the dreary details, but they
were mostly a drunken slur. I was officially sentenced to 1 year in a maximun security Jail called the Theo
Lacy Facility, I managed to get a job as a software engineer in Santa Monica where I had been living and
working for a year. Drinking and drinking is all I did. I would drink a High Gravity, a tall boy (24 oz) in
the morning, another one while riding my bike to work. And yeah, rinse and repeat! Somehow I wasn't fired
from that job, but managed to keep it until the start-up failed, maybe they failed because they choose
losers like myself! Anyways, things went sour and sour fast, and I moved back to my hometown of Watsonville
to live with my family and get things back together - so I thought.

\paragraph{}
To back up a little in my story, I want to discuss God leading me to another church that met on the UCI campus.
During the early times of beginning to attench Shepherds church, I was actually pursing a more convenient
church called the Summit. This is where I met Adam! Yep, that's right Mr. Chan! God also spoke to me
personally at this church. To be honest, I never knew the purpose of why God had sent me on the tangent of
seeking out church on my own and leading me specifically there, but it all makes sense now! It was to meet
Adam who would draw me into the next epoch of my life!


** Epoch of the Holy Spirit
\paragraph{}
Moving back home with my family to Watsonville actually didn't turn out to be such a good idea. The job
market here was horrible and I was unemployed for 6 months - the whole time I was applying for jobs, simple
ones that didn't even involve my degree. I got extremely depressed and I leaned even harder on the magical
medicine that I had been using for the past decade - alcohol. My drinking habit got really bad. It went from
drinking a six pack, to a twelve pack, and then to hard alcohol. And I would binge, drink like crazy for two
or three days and then quit for 3 days - it takes three days to recover, physiologically actually as I've
learned in practice and from discussion I've had with doctors. Anyways, my drinking go to the point where I
was literally drinking two 750 ml bottles in a sitting, and for all those who know the drinking terminology,
I was downing two handles a night by myself and in a single sitting. I was the fatest I had ever been,
weighing in at 310 lbs, with a waist size of 46! Stretch markes exploded everywhere - I hated myself. I felt
stupid, ugly, and incompetent!

\paragraph{}
Over this time period, Adam had reached out to me through Facebook and we met up. He actually encouraged me
to check out Freedom House, this was when they met up at Watsonville! I remember my first experience really
well, so well I could describe it with one word - weird! But you know what, God had planted a seed in my
heart, I knew I needed a miracle - and well I believed in the Holy Spirit and if there was anything to help
me at this point in life it would have to be the Holy Spirit.

\paragraph{}
My drinking was not just a physical problem, but an intense spiritual problem and at it's core there was a
major issue. I remember on the nights that I would decide I would stop drinking, I would be gripped by fear,
not be withdrawals or anything like that or shakes - I never had these, but nightmares. I would wake up in
the middle of the night being attached by aliens, as these creatures looked and strangling me! I became like
a child, I was scared of my closet. Also, I was defeated - I can't tell you how many times I tried to quit
and failed, I was losing all hope. That's how I ended up at drinking two handles a sitting, I actually
didn't want to wake up and I was to much of a sissy to kill myself directly, either way I figured it was
going to happen either quick in the night or slowly!

\paragraph{}
Then one night, something happened - I had been attacked beyond anything I have ever imagined. I drank so
brutally that I woke up to those aliens/demons and they were talking to me, even in the day time. I am not
going to go into what they were saying, but it was the most evil things about me I ever heard, to be honest
it's hard for me to admit this or tell it to anyone let alone write it down. I heard music coming from fans,
I'm surprised I went to work that day, but what was weird was when I went to work it stopped. I felt good
and I probably was going to drink that night when I got home. But... when I got home and stepped into my
house, they flooded back and this scared the daylights out of me. I prayed to God and spoke Jesus' name and
to be honest I don't know what I prayed. I then when out with my mom to get dinner, I had told her what was
going on the best I could, she prayed over me at dinner and when we got home everything was fine. But, I
woke up the next day and the hunger for alcohol was gone! My life changed beyond this point. I had a strong
will, I started working out lost all my weight. I believe that God healed me inside out that night. I've had
several blood tests since, my kidney and liver function are actually way better than my age. The doctors
were surprised, I have liver and kidney functionality of a 21 - 25 year old!

\paragraph{}
And here I am, God has called me to this church. I actually don't know why and I can't tell you the
specifics, but I just know in my heart. He has put a great yearning for the Holy Spirit and it's gifts. And
trust me, as a scientist this is hard to explain - but I can explain it if any of you are ever interesting
in my crazy theories. Anyways, I am glad to be here and God has restored my hope and I can't wait to see
what he is going to do next in my life! I want my heart to be ready like the disciples of Jesus, when he
asked them to go with him. I don't want to be among those that let ties to this world stop them from
following Jesus! I want to have faith that can move mountains, I want to see God as Moses did. I want to
have love in all things I do. And most importantly I want to do the will that God has set before my life!
When I get to heaven I want it to be written in the book of life that I was a faithful servant of Jesus!


* Ten Minute Version
\paragraph{}
TBD on what are the highlighted points of my testimony for this version...


* Three Minute Version
\paragraph{}
God called me at a very young age, I was in middle school when I first accepted Christ into my life - this
actually happened when I used to work with my Dad on the weekends, since my Mom and Dad divorced when I was
only four years old. It was at a church that gathered in a school cafeteria. Little did I know my life would
be forever changed beyond that point. Even though I never really commited to walk a life of faith, to say
the least my life lead down many temultous paths - shadows of the valley of death, if you will. Though, God
never left me - time and time again God would call and lead me back to him. 

\paragraph{}
Fast forward to present, God has called me back through Adam, and this has led me to a new epoch in my life,
one led by the Holy Spirit and many miracles to come. I have since been transformed, a decade long habit of
drinking instantenously removed - I almost don't even remember that I loved drinking, this in itself is
unimaginable. And secondly a complete physical transformation, my health has been completely restored, I
have lost 100 lbs, my asthma is completely gone. And God is working even more miracles in my life, right now
as we speak as you can see as I am here talking to you!

