#+TITLE: Prayer Notes
#+AUTHOR: Erik Almaraz
#+EMAIL: erik@almarazlabs.com
#+TODO: TODO FEEDBACK VERIFY | DONE CANCELED

* Prayer  Wed 2020.09.09

** Psalm 139:23-24 (KJV)
Search me, O God, and know my heart; try me, and know my thoughts: And see if
there be any wicked way in me, and lead me in the way everlasting.

Although, David was very sinful in nature we see from the story of David, or at
least I see, that sin isn't the the core of the problem and it must not be what
we focus on, but rather what is of upmost importance is the condition of our
hearts. We must always keep in prayer for God to reveal the condition of our
hearts so that they may remain childlike, earnest, and humble before the
Lord. Sin is easily treated, like a symptom, with repentance, however, if we
don't treat the root cause of the issue, our hearts, we'll keep stumbling over
the same sin or returning to sin in general. But once we ask God to treat our
hearts, can we truly repent and overcome sin - remember, we can only truly
overcome sin by the power of Christ and Christ alone! The core of every sin
lies in the state of our hearts.


* Prayer Mon 2020.09.14
** Psalm 91: 1-4 My Refuge and My Fortress (KJV)
"He that dwelleth in the secret place of the most High shall abide under the
shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress:
my God; in him will I trust. Surely he shall deliver thee from the snare of the
fowler, and from the noisome pestilence. He shall cover thee with his feathers,
and under his wings shalt thou trust: his truth shall be thy shield and buckler."

** Proverbs 4:20-24
"My son, attend to my words; inline thine ear unto my sayings.
Let them not depart from thine eyes; keep them in the midst of thine heart.
For they are life unto those that find them, and health to all their flesh.
Keepo thy heart with all diligence; for out of it are the issues of life.
Put away from thee a froward mouth, and perverse lips put far from thee."


* Prayer Tue 2020.09.15
** Matthew 6:31-34 (KJV)
"Therefore take no thought, saying, What shall we eat? or, What shall we drink?
or, Wherewithal shall we be clothed? (For after all these things do the Gentiles
seek:) for your heavenly Father knoweth that ye have need of all these
things. But seek ye first the kingdom of God, and his righteousness; and all
these things shall be added unto you. Take therefore no thought for the morrow:
for the morrow shall take thought for the things of itself. Sufficient unto the
day is the evil thereof."

Father, let me not worry and stress over what tomorrow may bring, but give me
solitude and soveriengty over my mind and peace that I may focus and seek first
your Kingdom and strive and work to have your righteousness...

** John 16:33 (KJV)
These things I have spoken unto you, that in me ye might have peace. In the world
ye shall have tribulation: but be of good cheer; I have overcome the world.




* Prayer Thu 2020.09.17
** Psalm 73:26-28 (KJV)
My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever. For, lo,
they that are far from thee shall perish: thou has destroyed all them that go a whoring from thee. But
it is good for me to draw near to God: I have put my trust in the LORD GOD, that I may declare all thy
works.



* Random Notes
The choosen - movie to watch  recommended by Adam.




